### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by YanWin** [YanWin/Hump_Jump_Replication#1]
Tasks:
- [ ]  Add relevant  functions to the HANKStickyAnalyticsClass
- [ ] Add modification to easily turn-off elastic investment
- [ ] Split Fiscal_Policy_Analysis.ipynb or reduce memory leakage
- [ ] Add permanent heterogeneity
- [ ] Adjust solver to allow for bounds
